jobs:
- job: copr_build
  trigger: pull_request
  metadata:
    targets:
    - fedora-all
    - epel-8-x86_64
    - centos-stream-8-x86_64
- job: tests
  trigger: pull_request
  metadata:
    targets:
    - fedora-all
    - epel-8-x86_64
    - centos-stream-8-x86_64

synced_files:
- tuned.spec
- .packit.yaml
